import Head from 'next/head'
import Image from 'next/image'
import { GetStaticProps } from 'next';
import { Inter } from 'next/font/google'
import styles from '@component/styles/Home.module.css'
import Link from 'next/link';
import utilStyles from '@component/styles/utils.module.css';
import MultiSearch from '@component/components/search-bar/MultiSearch';
import { fetchAllIngredients } from '@component/lib/ingredients';
import { Ingredient } from '@component/types/ingredients';

const inter = Inter({ subsets: ['latin'] })

export const getStaticProps: GetStaticProps = async () => {
  const ingredients = await fetchAllIngredients()
  return {
    props: {
      ingredients,
    },
  }
}


export default function Home({ ingredients }: any) {
  return (
    <>
      <Head>
        <title>Drinkee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={utilStyles.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
          <Link className={styles.card} href="/drinks">
            <h2 className={inter.className}>
              Drinks <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              View drinks list endpoint
            </p>
          </Link>
        </div>

        <div className={styles.searchBarFullWidth}>
          <MultiSearch items={ingredients} submitText="Search Available Cocktails" route="generateCocktails?strict=true" />
        </div>
      </main>
    </>
  )
}
